# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	if Vagrant.has_plugin? "vagrant-vbguest"
		config.vbguest.no_install = true
		config.vbguest.auto_update = false
		config.vbguest.no_remote = true
	end
		config.vm.define :firewall2 do |firewall2|
		firewall2.vm.box = "centos/stream8"    
		firewall2.vm.network :private_network, ip: "209.191.100.3"
		firewall2.vm.network :private_network, ip: "192.168.100.3"
		firewall2.vm.hostname = "firewall2"
		firewall2.vm.synced_folder ".", "/vagrant", type: "rsync"
	end
		config.vm.define :streaming do |streaming|
		streaming.vm.box = "centos/stream8"
		streaming.vm.network :private_network, ip: "192.168.100.4"
		streaming.vm.hostname = "streaming"
		streaming.vm.synced_folder ".", "/vagrant", type: "rsync"
	end
end
