# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	if Vagrant.has_plugin? "vagrant-vbguest"
		config.vbguest.no_install = true
		config.vbguest.auto_update = false
		config.vbguest.no_remote = true
	end
		config.vm.define :servidor3 do |servidor3|
		servidor3.vm.box = "centos/stream8"
		servidor3.vm.network :private_network, ip: "192.168.50.5"
		servidor3.vm.hostname = "servidor3"
		servidor3.vm.synced_folder ".", "/vagrant", type: "rsync"
		servidor3.vm.provision "shell", path: "script_servidor3.sh"
	end
		config.vm.define :servidor2 do |servidor2|
		servidor2.vm.box = "centos/stream8"
		servidor2.vm.network :private_network, ip: "192.168.50.4"
		servidor2.vm.hostname = "servidor2"
		servidor2.vm.synced_folder ".", "/vagrant", type: "rsync"
		servidor2.vm.provision "shell", path: "script_servidor2.sh"
	end
		config.vm.define :firewall do |firewall|
		firewall.vm.box = "centos/stream8"
		firewall.vm.network :private_network, ip: "192.168.50.3"
		firewall.vm.hostname = "firewall"
		firewall.vm.synced_folder ".", "/vagrant", type: "rsync"
		firewall.vm.provision "shell", path: "script_firewall.sh"
	end
end
